In [147]:
import numpy as np

In [148]:
x = np.array([3, 4, 5]) 
y = np.array([4, 9, 7])

In [149]:
x +y 

array([ 7, 13, 12])

In [150]:
x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [151]:
x.ndim

2

In [152]:
x.dtype

dtype('int64')

In [153]:
np.array([[1, 2], [3.0, 4]]).dtype

dtype('float64')

In [154]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [155]:
x.shape

(2, 2)

In [156]:
x = np.array([1, 2, 3, 4]) 
x.sum()

10

In [157]:
np.sum(x)

10

In [158]:
x = np.array([1,2,3,4,5,6])
print("at start x was : \n", x)
x_reshaped = x.reshape((2,3))
print("now after reshaping x is: \n", x_reshaped)

at start x was : 
 [1 2 3 4 5 6]
now after reshaping x is: 
 [[1 2 3]
 [4 5 6]]


In [159]:
x_reshaped[0][0]

1

In [160]:
x_reshaped[0][1], x_reshaped[1][2]

(2, 6)

In [161]:
x_reshaped[1,2]

6

- Therefore  : x_reshaped[1,2] = x_reshaped[1][2]

In [162]:
print("x before we modify x_reshape: \n", x)
print('x_reshape before we modify x_reshape:\n', x_reshaped) 
x_reshaped[0, 0] = 5
print('x_reshape after we modify its top left element:\n',x_reshaped)
print('x after we modify top left element of x_reshape:\n', x)


x before we modify x_reshape: 
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape:
 [5 2 3 4 5 6]


In [258]:
my_tuple = (3, 4, 5)
my_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment

In [259]:
x_reshaped.shape, x_reshaped.ndim, x_reshaped.T

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

In [165]:
np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [166]:
x**2

array([25,  4,  9, 16, 25, 36])

In [167]:
x**0.5

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [168]:
x = np.random.normal() 
x

1.1617674602318873

In [169]:
x = np.random.normal(10) 
x

9.757015814585444

In [170]:
x = np.random.normal(size= 10) 
x

array([ 0.68070866,  0.54420933,  1.26098321, -2.87435261,  0.27655565,
        0.28973159, -0.21845954, -0.85852665,  1.05396874, -1.19807812])

In [171]:
x = np.random.normal(size= (5,2)) 
x

array([[-2.14494839,  0.15910571],
       [-0.57273431,  0.71505072],
       [ 0.39916255, -1.47406242],
       [-0.29387901,  0.92703684],
       [ 1.05621927, -0.74143794]])

In [172]:
y = x + np.random.normal(loc = 0, scale = 1, size = (5,2))
y

array([[-3.22240304,  0.44726136],
       [-2.22652219,  0.37799602],
       [-0.45334327, -1.09871812],
       [ 0.10397482,  2.06452712],
       [ 0.48956757, -2.41509379]])

- #### Here  scale is std. deviation and  loc is mean.

In [173]:
np.corrcoef(x, y)

array([[ 1.,  1., -1.,  1., -1.,  1.,  1., -1.,  1., -1.],
       [ 1.,  1., -1.,  1., -1.,  1.,  1., -1.,  1., -1.],
       [-1., -1.,  1., -1.,  1., -1., -1.,  1., -1.,  1.],
       [ 1.,  1., -1.,  1., -1.,  1.,  1., -1.,  1., -1.],
       [-1., -1.,  1., -1.,  1., -1., -1.,  1., -1.,  1.],
       [ 1.,  1., -1.,  1., -1.,  1.,  1., -1.,  1., -1.],
       [ 1.,  1., -1.,  1., -1.,  1.,  1., -1.,  1., -1.],
       [-1., -1.,  1., -1.,  1., -1., -1.,  1., -1.,  1.],
       [ 1.,  1., -1.,  1., -1.,  1.,  1., -1.,  1., -1.],
       [-1., -1.,  1., -1.,  1., -1., -1.,  1., -1.,  1.]])

In [174]:
print(np.random.normal(loc =1, scale=1, size=(2,2)))
print(np.random.normal(loc =1, scale=1, size=(2,2)))

[[ 1.97591948  1.03271761]
 [ 0.6250633  -0.18364446]]
[[-1.19071833 -0.15564973]
 [ 0.60248167  1.23003736]]


- Each randfom generator produces different set values
- To solve this we will use rng.
- we use np.random.default_rng() when- ever we perform calculations involving random quantities within numpy. In principle, this should enable the reader to exactly reproduce the stated results.

In [175]:
rng = np.random.default_rng(1) 
print(rng.normal(loc = 100, scale=2, size=(1,2))) 
rng2 = np.random.default_rng(1) 
print(rng2.normal(loc = 100, scale=2, size=(1,2)))

[[100.69116838 101.64323629]]
[[100.69116838 101.64323629]]


In [176]:
rng = np.random.default_rng(2) 
y = rng.standard_normal(15)
np.mean(y), y.mean()

(-0.0045055220957680555, -0.0045055220957680555)

In [177]:
np.var(y), y.var(), np.mean((y - y.mean())**2)

(0.9382211403909403, 0.9382211403909403, 0.9382211403909403)

In [178]:
 np.sqrt(np.var(y)), np.std(y)

(0.9686181602628253, 0.9686181602628253)

In [179]:
x = rng.standard_normal((2, 3)) 
x

array([[-0.09919805,  0.54528871, -0.6071857 ],
       [ 0.12682785, -0.89227404,  0.84146497]])

In [180]:
x.mean(axis = 0)
# along t5he rows

array([ 0.0138149 , -0.17349266,  0.11713964])

In [181]:
x.mean(axis =1)

array([-0.05369835,  0.02533959])

### Indexing the Data:

In [182]:
A = np.array(np.arange(9).reshape(3,3))

In [183]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [184]:
 A[1,2]

5

In [185]:
A[[0,2]]#this will provide multiple rows at same time with the index= 0 & 2

array([[0, 1, 2],
       [6, 7, 8]])

In [186]:
 A[[0,2],[0,2]]

array([0, 8])

In [187]:
np.array(A[[0,2],[0,2]])

array([0, 8])

In [188]:
A[[1,2],[2,2]]

array([5, 8])

In [189]:
A[[0,2]][:,[0,2]]

array([[0, 2],
       [6, 8]])

In [190]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [191]:
idx = np.ix_([0,2],[0,1,2]) 
A[idx]

array([[0, 1, 2],
       [6, 7, 8]])

In [192]:
A[:,[0,1]] # entire rows with 0th and 1st column

array([[0, 1],
       [3, 4],
       [6, 7]])

In [193]:
A = np.array(np.arange(16).reshape(4,4))

In [194]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [195]:
 A[1:4:2,0:3:2]

array([[ 4,  6],
       [12, 14]])

In [196]:
A.shape[0]

4

In [197]:
keep_rows = np.zeros(A.shape[0], bool) 
keep_rows

array([False, False, False, False])

In [198]:
keep_rows[[1,3]] = True 
keep_rows

array([False,  True, False,  True])

In [199]:
np.all(keep_rows == np.array([0,1,0,1]))

True

In [200]:
 A[np.array([0,1,0,1])]

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [201]:
A[keep_rows]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [202]:
keep_cols = np.zeros(A.shape[1], bool) 

In [203]:
keep_cols

array([False, False, False, False])

In [204]:
keep_cols[[0, 2, 3]] = True

In [205]:
keep_cols

array([ True, False,  True,  True])

In [206]:
keep_rows

array([False,  True, False,  True])

In [207]:
idx_bool = np.ix_(keep_rows, keep_cols)

In [208]:
idx_bool

(array([[1],
        [3]]),
 array([[0, 2, 3]]))

In [209]:
keep_cols = np.zeros(A.shape[1], bool) 
keep_cols[[0, 2, 3]] = True
idx_bool = np.ix_(keep_rows, keep_cols) 
A[idx_bool]

array([[ 4,  6,  7],
       [12, 14, 15]])

In [210]:
idx_mixed = np.ix_([1,3], keep_cols)
A[idx_mixed]

array([[ 4,  6,  7],
       [12, 14, 15]])

In [211]:
bool

bool

### 2.3.7 Loading Data 

In [212]:
import pandas as pd

In [213]:
Auto = pd.read_csv('Auto.data', delim_whitespace=True)

In [214]:
Auto = pd.read_csv("Auto.csv")

In [215]:
Auto.head()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  18.0          8         307.0        130    3504          12.0    70   
1  15.0          8         350.0        165    3693          11.5    70   
2  18.0          8         318.0        150    3436          11.0    70   
3  16.0          8         304.0        150    3433          12.0    70   
4  17.0          8         302.0        140    3449          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [216]:
Auto['horsepower']

0      130
1      165
2      150
3      150
4      140
      ... 
392     86
393     52
394     84
395     79
396     82
Name: horsepower, Length: 397, dtype: object

In [217]:
np.unique(Auto['horsepower'])

array(['100', '102', '103', '105', '107', '108', '110', '112', '113',
       '115', '116', '120', '122', '125', '129', '130', '132', '133',
       '135', '137', '138', '139', '140', '142', '145', '148', '149',
       '150', '152', '153', '155', '158', '160', '165', '167', '170',
       '175', '180', '190', '193', '198', '200', '208', '210', '215',
       '220', '225', '230', '46', '48', '49', '52', '53', '54', '58',
       '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70',
       '71', '72', '74', '75', '76', '77', '78', '79', '80', '81', '82',
       '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93',
       '94', '95', '96', '97', '98', '?'], dtype=object)

In [218]:
Auto['horsepower'].sum()

'13016515015014019822021522519017016015022595959785884687909511390215200210193889095?1001051008810016517515315018017017511072100888690707665696070958054908616517515015315020815516019097150130140150112768769869297808817515014513715019815015815021522517510510010088954615016717018010088729490851079014523049759111215011012218095?100100678065751001101051401501501401508367785261757575979367951057272170145150148110105110951101101297583100789671979770909588981155386819279831401501201521001058190526070531007811095717075721021508810812018014513015068805896701451101451301101051009818017019014978887589638367789711011048665270601101401391059585881009010585110120145165139140689597759510585971031251151337168115858890110130129138135155142125150716580807712571907070656990115115907660706590889090789075927565105654848676767?676213210088?72848492110845864606765626863656574?7575100748076116120110105888588888885849092746868637088757067676711085921129684908652847982'

- #### Here missing value is replace by an "?". It is the culprit for such large no.

In [219]:
Auto = pd.read_csv("Auto.csv", na_values=['?'])

In [220]:
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'list[HashableT] | Callable[[Hashable], bool] | None' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Sequence[str] | Mapping[str, Sequence[str]] | None' = None,
    keep_default_na: 'bool' = True,
    n

In [221]:
np.unique(Auto['horsepower'])

array([ 46.,  48.,  49.,  52.,  53.,  54.,  58.,  60.,  61.,  62.,  63.,
        64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,  74.,  75.,
        76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,
        87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,
        98., 100., 102., 103., 105., 107., 108., 110., 112., 113., 115.,
       116., 120., 122., 125., 129., 130., 132., 133., 135., 137., 138.,
       139., 140., 142., 145., 148., 149., 150., 152., 153., 155., 158.,
       160., 165., 167., 170., 175., 180., 190., 193., 198., 200., 208.,
       210., 215., 220., 225., 230.,  nan])

In [222]:
Auto['horsepower'].sum()

40952.0

In [223]:
Auto.shape

(397, 9)

In [224]:
Auto_new = Auto.dropna()

In [225]:
Auto_new.shape # flawed rows with no data

(392, 9)

In [226]:
Auto_new_WITHOUTDUBLICATES = Auto_new.drop_duplicates

In [227]:
Auto_new_WITHOUTDUBLICATES

<bound method DataFrame.drop_duplicates of       mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0    18.0          8         307.0       130.0    3504          12.0    70   
1    15.0          8         350.0       165.0    3693          11.5    70   
2    18.0          8         318.0       150.0    3436          11.0    70   
3    16.0          8         304.0       150.0    3433          12.0    70   
4    17.0          8         302.0       140.0    3449          10.5    70   
..    ...        ...           ...         ...     ...           ...   ...   
392  27.0          4         140.0        86.0    2790          15.6    82   
393  44.0          4          97.0        52.0    2130          24.6    82   
394  32.0          4         135.0        84.0    2295          11.6    82   
395  28.0          4         120.0        79.0    2625          18.6    82   
396  31.0          4         119.0        82.0    2720          19.4    82   

     origin         

### There are no dublicate data

### Basics of selecting rows and columns :

In [228]:
Auto = Auto_new

In [229]:
Auto.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin', 'name'],
      dtype='object')

In [230]:
Auto[0:3]

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0       130.0    3504          12.0    70   
1  15.0          8         350.0       165.0    3693          11.5    70   
2  18.0          8         318.0       150.0    3436          11.0    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite

In [231]:
idx_81 = Auto['year'] > 81

In [232]:
Auto[idx_81]

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
367  28.0          4         112.0        88.0    2605          19.6    82   
368  27.0          4         112.0        88.0    2640          18.6    82   
369  34.0          4         112.0        88.0    2395          18.0    82   
370  31.0          4         112.0        85.0    2575          16.2    82   
371  29.0          4         135.0        84.0    2525          16.0    82   
372  27.0          4         151.0        90.0    2735          18.0    82   
373  24.0          4         140.0        92.0    2865          16.4    82   
374  36.0          4         105.0        74.0    1980          15.3    82   
375  37.0          4          91.0        68.0    2025          18.2    82   
376  31.0          4          91.0        68.0    1970          17.6    82   
377  38.0          4         105.0        63.0    2125          14.7    82   
378  36.0          4          98.0        70.0    2125          17.3    82   
379  36.0          4         120.0        88.0    2160          14.5    82   
380  36.0          4         107.0        75.0    2205          14.5    82   
381  34.0          4         108.0        70.0    2245          16.9    82   
382  38.0          4          91.0        67.0    1965          15.0    82   
383  32.0          4          91.0        67.0    1965          15.7    82   
384  38.0          4          91.0        67.0    1995          16.2    82   
385  25.0          6         181.0       110.0    2945          16.4    82   
386  38.0          6         262.0        85.0    3015          17.0    82   
387  26.0          4         156.0        92.0    2585          14.5    82   
388  22.0          6         232.0       112.0    2835          14.7    82   
389  32.0          4         144.0        96.0    2665          13.9    82   
390  36.0          4         135.0        84.0    2370          13.0    82   
391  27.0          4         151.0        90.0    2950          17.3    82   
392  27.0          4         140.0        86.0    2790          15.6    82   
393  44.0          4          97.0        52.0    2130          24.6    82   
394  32.0          4         135.0        84.0    2295          11.6    82   
395  28.0          4         120.0        79.0    2625          18.6    82   
396  31.0          4         119.0        82.0    2720          19.4    82   

     origin                               name  
367       1                 chevrolet cavalier  
368       1           chevrolet cavalier wagon  
369       1          chevrolet cavalier 2-door  
370       1         pontiac j2000 se hatchback  
371       1                     dodge aries se  
372       1                    pontiac phoenix  
373       1               ford fairmont futura  
374       2                volkswagen rabbit l  
375       3                 mazda glc custom l  
376       3                   mazda glc custom  
377       1             plymouth horizon miser  
378       1                     mercury lynx l  
379       3                   nissan stanza xe  
380       3                       honda accord  
381       3                     toyota corolla  
382       3                        honda civic  
383       3                 honda civic (auto)  
384       3                      datsun 310 gx  
385       1              buick century limited  
386       1  oldsmobile cutlass ciera (diesel)  
387       1         chrysler lebaron medallion  
388       1                     ford granada l  
389       3                   toyota celica gt  
390       1                  dodge charger 2.2  
391       1                   chevrolet camaro  
392       1                    ford mustang gl  
393       2                          vw pickup  
394       1                      dodge rampage  
395       1                        ford ranger  
396       1                         chevy s-10

In [233]:
Auto[["horsepower", "weight", "displacement"]]
# passing as a list

horsepower  weight  displacement
0         130.0    3504         307.0
1         165.0    3693         350.0
2         150.0    3436         318.0
3         150.0    3433         304.0
4         140.0    3449         302.0
..          ...     ...           ...
392        86.0    2790         140.0
393        52.0    2130          97.0
394        84.0    2295         135.0
395        79.0    2625         120.0
396        82.0    2720         119.0

[392 rows x 3 columns]

In [234]:
Auto.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       387, 388, 389, 390, 391, 392, 393, 394, 395, 396],
      dtype='int64', length=392)

In [235]:
Auto_indexing_using_name = Auto.set_index("name")
Auto_indexing_using_name

mpg  cylinders  displacement  horsepower  weight  \
name                                                                           
chevrolet chevelle malibu  18.0          8         307.0       130.0    3504   
buick skylark 320          15.0          8         350.0       165.0    3693   
plymouth satellite         18.0          8         318.0       150.0    3436   
amc rebel sst              16.0          8         304.0       150.0    3433   
ford torino                17.0          8         302.0       140.0    3449   
...                         ...        ...           ...         ...     ...   
ford mustang gl            27.0          4         140.0        86.0    2790   
vw pickup                  44.0          4          97.0        52.0    2130   
dodge rampage              32.0          4         135.0        84.0    2295   
ford ranger                28.0          4         120.0        79.0    2625   
chevy s-10                 31.0          4         119.0        82.0    2720   

                           acceleration  year  origin  
name                                                   
chevrolet chevelle malibu          12.0    70       1  
buick skylark 320                  11.5    70       1  
plymouth satellite                 11.0    70       1  
amc rebel sst                      12.0    70       1  
ford torino                        10.5    70       1  
...                                 ...   ...     ...  
ford mustang gl                    15.6    82       1  
vw pickup                          24.6    82       2  
dodge rampage                      11.6    82       1  
ford ranger                        18.6    82       1  
chevy s-10                         19.4    82       1  

[392 rows x 8 columns]

In [236]:
Auto_indexing_using_name.columns
# Name is no longer there

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin'],
      dtype='object')

In [237]:
rows = ['amc rebel sst', 'ford torino']
Auto_indexing_using_name.loc[rows]

mpg  cylinders  displacement  horsepower  weight  \
name                                                               
amc rebel sst  16.0          8         304.0       150.0    3433   
ford torino    17.0          8         302.0       140.0    3449   

               acceleration  year  origin  
name                                       
amc rebel sst          12.0    70       1  
ford torino            10.5    70       1

In [238]:
Auto_indexing_using_name.iloc[[3,4]]

mpg  cylinders  displacement  horsepower  weight  \
name                                                               
amc rebel sst  16.0          8         304.0       150.0    3433   
ford torino    17.0          8         302.0       140.0    3449   

               acceleration  year  origin  
name                                       
amc rebel sst          12.0    70       1  
ford torino            10.5    70       1

In [239]:
Auto_indexing_using_name.iloc[:,[0,2,3]]

mpg  displacement  horsepower
name                                                     
chevrolet chevelle malibu  18.0         307.0       130.0
buick skylark 320          15.0         350.0       165.0
plymouth satellite         18.0         318.0       150.0
amc rebel sst              16.0         304.0       150.0
ford torino                17.0         302.0       140.0
...                         ...           ...         ...
ford mustang gl            27.0         140.0        86.0
vw pickup                  44.0          97.0        52.0
dodge rampage              32.0         135.0        84.0
ford ranger                28.0         120.0        79.0
chevy s-10                 31.0         119.0        82.0

[392 rows x 3 columns]

In [240]:
Auto_indexing_using_name.iloc[[3,4],[0,2,3]]

mpg  displacement  horsepower
name                                         
amc rebel sst  16.0         304.0       150.0
ford torino    17.0         302.0       140.0

In [241]:
Auto_indexing_using_name.loc['ford galaxie 500', ['mpg', 'origin']]

mpg  origin
name                          
ford galaxie 500  15.0       1
ford galaxie 500  14.0       1
ford galaxie 500  14.0       1

In [242]:
idx_80 = Auto_indexing_using_name['year'] > 80 
Auto_indexing_using_name.loc[idx_80, ['weight', 'origin']]

weight  origin
name                                             
plymouth reliant                     2490       1
buick skylark                        2635       1
dodge aries wagon (sw)               2620       1
chevrolet citation                   2725       1
plymouth reliant                     2385       1
toyota starlet                       1755       3
plymouth champ                       1875       1
honda civic 1300                     1760       3
subaru                               2065       3
datsun 210 mpg                       1975       3
toyota tercel                        2050       3
mazda glc 4                          1985       3
plymouth horizon 4                   2215       1
ford escort 4w                       2045       1
ford escort 2h                       2380       1
volkswagen jetta                     2190       2
honda prelude                        2210       3
toyota corolla                       2350       3
datsun 200sx                         2615       3
mazda 626                            2635       3
peugeot 505s turbo diesel            3230       2
volvo diesel                         3160       2
toyota cressida                      2900       3
datsun 810 maxima                    2930       3
buick century                        3415       1
oldsmobile cutlass ls                3725       1
ford granada gl                      3060       1
chrysler lebaron salon               3465       1
chevrolet cavalier                   2605       1
chevrolet cavalier wagon             2640       1
chevrolet cavalier 2-door            2395       1
pontiac j2000 se hatchback           2575       1
dodge aries se                       2525       1
pontiac phoenix                      2735       1
ford fairmont futura                 2865       1
volkswagen rabbit l                  1980       2
mazda glc custom l                   2025       3
mazda glc custom                     1970       3
plymouth horizon miser               2125       1
mercury lynx l                       2125       1
nissan stanza xe                     2160       3
honda accord                         2205       3
toyota corolla                       2245       3
honda civic                          1965       3
honda civic (auto)                   1965       3
datsun 310 gx                        1995       3
buick century limited                2945       1
oldsmobile cutlass ciera (diesel)    3015       1
chrysler lebaron medallion           2585       1
ford granada l                       2835       1
toyota celica gt                     2665       3
dodge charger 2.2                    2370       1
chevrolet camaro                     2950       1
ford mustang gl                      2790       1
vw pickup                            2130       2
dodge rampage                        2295       1
ford ranger                          2625       1
chevy s-10                           2720       1

In [243]:
Auto_indexing_using_name.loc[lambda df: df['year'] > 80, ['weight', 'origin']]

weight  origin
name                                             
plymouth reliant                     2490       1
buick skylark                        2635       1
dodge aries wagon (sw)               2620       1
chevrolet citation                   2725       1
plymouth reliant                     2385       1
toyota starlet                       1755       3
plymouth champ                       1875       1
honda civic 1300                     1760       3
subaru                               2065       3
datsun 210 mpg                       1975       3
toyota tercel                        2050       3
mazda glc 4                          1985       3
plymouth horizon 4                   2215       1
ford escort 4w                       2045       1
ford escort 2h                       2380       1
volkswagen jetta                     2190       2
honda prelude                        2210       3
toyota corolla                       2350       3
datsun 200sx                         2615       3
mazda 626                            2635       3
peugeot 505s turbo diesel            3230       2
volvo diesel                         3160       2
toyota cressida                      2900       3
datsun 810 maxima                    2930       3
buick century                        3415       1
oldsmobile cutlass ls                3725       1
ford granada gl                      3060       1
chrysler lebaron salon               3465       1
chevrolet cavalier                   2605       1
chevrolet cavalier wagon             2640       1
chevrolet cavalier 2-door            2395       1
pontiac j2000 se hatchback           2575       1
dodge aries se                       2525       1
pontiac phoenix                      2735       1
ford fairmont futura                 2865       1
volkswagen rabbit l                  1980       2
mazda glc custom l                   2025       3
mazda glc custom                     1970       3
plymouth horizon miser               2125       1
mercury lynx l                       2125       1
nissan stanza xe                     2160       3
honda accord                         2205       3
toyota corolla                       2245       3
honda civic                          1965       3
honda civic (auto)                   1965       3
datsun 310 gx                        1995       3
buick century limited                2945       1
oldsmobile cutlass ciera (diesel)    3015       1
chrysler lebaron medallion           2585       1
ford granada l                       2835       1
toyota celica gt                     2665       3
dodge charger 2.2                    2370       1
chevrolet camaro                     2950       1
ford mustang gl                      2790       1
vw pickup                            2130       2
dodge rampage                        2295       1
ford ranger                          2625       1
chevy s-10                           2720       1

In [244]:
Auto_indexing_using_name.loc[lambda df: (df['year'] > 80) & (df['mpg'] > 30),
['weight', 'origin'] ]

weight  origin
name                                             
toyota starlet                       1755       3
plymouth champ                       1875       1
honda civic 1300                     1760       3
subaru                               2065       3
datsun 210 mpg                       1975       3
toyota tercel                        2050       3
mazda glc 4                          1985       3
plymouth horizon 4                   2215       1
ford escort 4w                       2045       1
volkswagen jetta                     2190       2
honda prelude                        2210       3
toyota corolla                       2350       3
datsun 200sx                         2615       3
mazda 626                            2635       3
volvo diesel                         3160       2
chevrolet cavalier 2-door            2395       1
pontiac j2000 se hatchback           2575       1
volkswagen rabbit l                  1980       2
mazda glc custom l                   2025       3
mazda glc custom                     1970       3
plymouth horizon miser               2125       1
mercury lynx l                       2125       1
nissan stanza xe                     2160       3
honda accord                         2205       3
toyota corolla                       2245       3
honda civic                          1965       3
honda civic (auto)                   1965       3
datsun 310 gx                        1995       3
oldsmobile cutlass ciera (diesel)    3015       1
toyota celica gt                     2665       3
dodge charger 2.2                    2370       1
vw pickup                            2130       2
dodge rampage                        2295       1
chevy s-10                           2720       1

In [245]:
Auto_indexing_using_name.loc[lambda df: (df['year'] > 80) & (df['mpg'] > 30),
['weight', 'origin'] ]

weight  origin
name                                             
toyota starlet                       1755       3
plymouth champ                       1875       1
honda civic 1300                     1760       3
subaru                               2065       3
datsun 210 mpg                       1975       3
toyota tercel                        2050       3
mazda glc 4                          1985       3
plymouth horizon 4                   2215       1
ford escort 4w                       2045       1
volkswagen jetta                     2190       2
honda prelude                        2210       3
toyota corolla                       2350       3
datsun 200sx                         2615       3
mazda 626                            2635       3
volvo diesel                         3160       2
chevrolet cavalier 2-door            2395       1
pontiac j2000 se hatchback           2575       1
volkswagen rabbit l                  1980       2
mazda glc custom l                   2025       3
mazda glc custom                     1970       3
plymouth horizon miser               2125       1
mercury lynx l                       2125       1
nissan stanza xe                     2160       3
honda accord                         2205       3
toyota corolla                       2245       3
honda civic                          1965       3
honda civic (auto)                   1965       3
datsun 310 gx                        1995       3
oldsmobile cutlass ciera (diesel)    3015       1
toyota celica gt                     2665       3
dodge charger 2.2                    2370       1
vw pickup                            2130       2
dodge rampage                        2295       1
chevy s-10                           2720       1

In [246]:
Auto_indexing_using_name.loc[lambda df: (df['displacement'] < 300)
& (df.index.str.contains('ford')
| df.index.str.contains('datsun')), ['weight', 'origin']
]

weight  origin
name                                 
ford maverick            2587       1
datsun pl510             2130       3
datsun pl510             2130       3
ford torino 500          3302       1
ford mustang             3139       1
datsun 1200              1613       3
ford pinto runabout      2226       1
ford pinto (sw)          2395       1
datsun 510 (sw)          2288       3
ford maverick            3021       1
datsun 610               2379       3
ford pinto               2310       1
datsun b210              1950       3
ford pinto               2451       1
datsun 710               2003       3
ford maverick            3158       1
ford pinto               2639       1
datsun 710               2545       3
ford pinto               2984       1
ford maverick            3012       1
ford granada ghia        3574       1
datsun b-210             1990       3
ford pinto               2565       1
datsun f-10 hatchback    1945       3
ford granada             3525       1
ford mustang ii 2+2      2755       1
datsun 810               2815       3
ford fiesta              1800       1
datsun b210 gx           2070       3
ford fairmont (auto)     2965       1
ford fairmont (man)      2720       1
datsun 510               2300       3
datsun 200-sx            2405       3
ford fairmont 4          2890       1
datsun 210               2020       3
datsun 310               2019       3
ford fairmont            2870       1
datsun 510 hatchback     2434       3
datsun 210               2110       3
datsun 280-zx            2910       3
datsun 210 mpg           1975       3
ford escort 4w           2045       1
ford escort 2h           2380       1
datsun 200sx             2615       3
datsun 810 maxima        2930       3
ford granada gl          3060       1
ford fairmont futura     2865       1
datsun 310 gx            1995       3
ford granada l           2835       1
ford mustang gl          2790       1
ford ranger              2625       1

### Exercises: 8 a-c

In [247]:
college = pd.read_csv("College.csv")

In [248]:
college.head()

Unnamed: 0 Private  Apps  Accept  Enroll  Top10perc  \
0  Abilene Christian University     Yes  1660    1232     721         23   
1            Adelphi University     Yes  2186    1924     512         16   
2                Adrian College     Yes  1428    1097     336         22   
3           Agnes Scott College     Yes   417     349     137         60   
4     Alaska Pacific University     Yes   193     146      55         16   

   Top25perc  F.Undergrad  P.Undergrad  Outstate  Room.Board  Books  Personal  \
0         52         2885          537      7440        3300    450      2200   
1         29         2683         1227     12280        6450    750      1500   
2         50         1036           99     11250        3750    400      1165   
3         89          510           63     12960        5450    450       875   
4         44          249          869      7560        4120    800      1500   

   PhD  Terminal  S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0   70        78       18.1           12    7041         60  
1   29        30       12.2           16   10527         56  
2   53        66       12.9           30    8735         54  
3   92        97        7.7           37   19016         59  
4   76        72       11.9            2   10922         15

In [249]:
college2 = pd.read_csv('College.csv', index_col=0) 

In [250]:
college2.head()

Private  Apps  Accept  Enroll  Top10perc  \
Abilene Christian University     Yes  1660    1232     721         23   
Adelphi University               Yes  2186    1924     512         16   
Adrian College                   Yes  1428    1097     336         22   
Agnes Scott College              Yes   417     349     137         60   
Alaska Pacific University        Yes   193     146      55         16   

                              Top25perc  F.Undergrad  P.Undergrad  Outstate  \
Abilene Christian University         52         2885          537      7440   
Adelphi University                   29         2683         1227     12280   
Adrian College                       50         1036           99     11250   
Agnes Scott College                  89          510           63     12960   
Alaska Pacific University            44          249          869      7560   

                              Room.Board  Books  Personal  PhD  Terminal  \
Abilene Christian University        3300    450      2200   70        78   
Adelphi University                  6450    750      1500   29        30   
Adrian College                      3750    400      1165   53        66   
Agnes Scott College                 5450    450       875   92        97   
Alaska Pacific University           4120    800      1500   76        72   

                              S.F.Ratio  perc.alumni  Expend  Grad.Rate  
Abilene Christian University       18.1           12    7041         60  
Adelphi University                 12.2           16   10527         56  
Adrian College                     12.9           30    8735         54  
Agnes Scott College                 7.7           37   19016         59  
Alaska Pacific University          11.9            2   10922         15

In [251]:
college3 = college.rename({'Unnamed: 0': 'College'},axis=1)

In [252]:
college3.head()

College Private  Apps  Accept  Enroll  Top10perc  \
0  Abilene Christian University     Yes  1660    1232     721         23   
1            Adelphi University     Yes  2186    1924     512         16   
2                Adrian College     Yes  1428    1097     336         22   
3           Agnes Scott College     Yes   417     349     137         60   
4     Alaska Pacific University     Yes   193     146      55         16   

   Top25perc  F.Undergrad  P.Undergrad  Outstate  Room.Board  Books  Personal  \
0         52         2885          537      7440        3300    450      2200   
1         29         2683         1227     12280        6450    750      1500   
2         50         1036           99     11250        3750    400      1165   
3         89          510           63     12960        5450    450       875   
4         44          249          869      7560        4120    800      1500   

   PhD  Terminal  S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0   70        78       18.1           12    7041         60  
1   29        30       12.2           16   10527         56  
2   53        66       12.9           30    8735         54  
3   92        97        7.7           37   19016         59  
4   76        72       11.9            2   10922         15

In [253]:
 college3 = college3.set_index('College')

In [254]:
college3.head()

Private  Apps  Accept  Enroll  Top10perc  \
College                                                                 
Abilene Christian University     Yes  1660    1232     721         23   
Adelphi University               Yes  2186    1924     512         16   
Adrian College                   Yes  1428    1097     336         22   
Agnes Scott College              Yes   417     349     137         60   
Alaska Pacific University        Yes   193     146      55         16   

                              Top25perc  F.Undergrad  P.Undergrad  Outstate  \
College                                                                       
Abilene Christian University         52         2885          537      7440   
Adelphi University                   29         2683         1227     12280   
Adrian College                       50         1036           99     11250   
Agnes Scott College                  89          510           63     12960   
Alaska Pacific University            44          249          869      7560   

                              Room.Board  Books  Personal  PhD  Terminal  \
College                                                                    
Abilene Christian University        3300    450      2200   70        78   
Adelphi University                  6450    750      1500   29        30   
Adrian College                      3750    400      1165   53        66   
Agnes Scott College                 5450    450       875   92        97   
Alaska Pacific University           4120    800      1500   76        72   

                              S.F.Ratio  perc.alumni  Expend  Grad.Rate  
College                                                                  
Abilene Christian University       18.1           12    7041         60  
Adelphi University                 12.2           16   10527         56  
Adrian College                     12.9           30    8735         54  
Agnes Scott College                 7.7           37   19016         59  
Alaska Pacific University          11.9            2   10922         15

In [255]:
college = college3

In [256]:
college.head() ## type key : value 
# where keys are college name and else are its attributes

Private  Apps  Accept  Enroll  Top10perc  \
College                                                                 
Abilene Christian University     Yes  1660    1232     721         23   
Adelphi University               Yes  2186    1924     512         16   
Adrian College                   Yes  1428    1097     336         22   
Agnes Scott College              Yes   417     349     137         60   
Alaska Pacific University        Yes   193     146      55         16   

                              Top25perc  F.Undergrad  P.Undergrad  Outstate  \
College                                                                       
Abilene Christian University         52         2885          537      7440   
Adelphi University                   29         2683         1227     12280   
Adrian College                       50         1036           99     11250   
Agnes Scott College                  89          510           63     12960   
Alaska Pacific University            44          249          869      7560   

                              Room.Board  Books  Personal  PhD  Terminal  \
College                                                                    
Abilene Christian University        3300    450      2200   70        78   
Adelphi University                  6450    750      1500   29        30   
Adrian College                      3750    400      1165   53        66   
Agnes Scott College                 5450    450       875   92        97   
Alaska Pacific University           4120    800      1500   76        72   

                              S.F.Ratio  perc.alumni  Expend  Grad.Rate  
College                                                                  
Abilene Christian University       18.1           12    7041         60  
Adelphi University                 12.2           16   10527         56  
Adrian College                     12.9           30    8735         54  
Agnes Scott College                 7.7           37   19016         59  
Alaska Pacific University          11.9            2   10922         15

In [257]:
college.describe(axis = 1)

TypeError: NDFrame.describe() got an unexpected keyword argument 'axis'